package ie.gmit.sw;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;

//- ResultatorImpl extends UnicastRemoteObject and implements the methods of Resultator.
public class ResultatorImpl extends UnicastRemoteObject implements Resultator {

	private static final long serialVersionUID = 1L;
	
	//- Variables created to be used in the generated methods.
	private String result;
	private boolean process;
	
	public ResultatorImpl() throws RemoteException {
		super();
	}
	
	//- Methods generated by Resultator using Source->Override/Implement Methods...
	@Override
	public String getResult() throws RemoteException {
		return result;
	}//- End of getResult

	@Override
	public void setResult(String result) throws RemoteException {
		this.result  = result;
	}//- End of setResult

	@Override
	public boolean isProcessed() throws RemoteException {
		return process;
	}//- End of isProcessed

	@Override
	public void setProcessed() throws RemoteException {
		this.process = true;
	}//- End of setProcessed
}//- End of ResultatorImpl
